#[[plugins]]
#repo = 'zchee/deoplete-clang'
#on_ft = ['c', 'cpp', 'cc', 'cmake']
#depends = ['deoplete.nvim']
#hook_source = '''
#    let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-4.0/lib/libclang.so'
#    let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
#'''
[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp', 'cc']
hook_source = '''
let g:clang_cpp_options = '-std=c++14'
'''
#[[plugins]]
#repo = 'Shougo/neoinclude.vim'
#on_ft = ['c', 'cpp', 'cc', 'cmake']
#depends = ['deoplete.nvim']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'nsf/gocode'
on_ft = 'go'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
let g:go_fmt_command = "goimports"
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_term_enabled = 1
let g:go_highlight_build_constraints = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'
on_i = 1
on_ft = 'go'
hook_source='''
let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
let g:deoplete#sources#go#package_dot = 1
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
let g:deoplete#sources#go#pointer = 1
let g:deoplete#sources#go#cgo = 0
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  source ~/.vim/rc/plugins/deoplete.rc.vim
'''

#[[plugins]]
#repo = 'vhdirk/vim-cmake'
#hook_source = '''
#let g:cmake_build_type = 'Debug'
#let g:cmake_build_dir = 'bin'
#'''


