#!/bin/bash -e

declare -A commands=(
["default"]="$AURHELPER -S --noconfirm --needed"
["pip3"]="sudo pip3 install"
["npm"]="npm install -g"
["gem"]="gem install --user-install --no-document"
)

cli=(arch-install-scripts atool bc boost clang cmake colordiff cronie ctags  \
    docker docker-compose dmidecode docx2txt editorconfig-core-c             \
    ethtool exa exfat-utils expect  \
    findutils fzf gettext git git-lfs git-secrets go                         \
    gvfs-smb highlight htop hub imagemagick imlib2 intel-ucode jq keychain   \
    linux-headers mercurial mlocate moreutils multitail neomutt              \
    neovim npm ntfs-3g ntp num-utils numlockx nodejs-lts-carbon openssh      \
    otf-ipaexfont pacman-contrib pandoc pass pdftk-bin pv python python-pip  \
    python2-pip ranger rbenv                                                 \
    rsync ruby sc screenfetch shellcheck sqlite tcpdump the_silver_searcher  \
    tig tmux trash-cli ufw unarchiver w3m wget whois xorg-xrandr zsh)
gui=(alsa-utils avahi cups cups-pdf gimp gnome-keyring google-chrome         \
    gparted graphviz gtk3-print-backends gufw libdvdcss                      \
    libreoffice-fresh libreoffice-fresh-ja lightdm lightdm-gtk-greeter maim  \
    mate mate-extra mesa noto-fonts noto-fonts-cjk noto-fonts-emoji          \
    noto-fonts-extra nss-mdns                                                \
    otf-ipafont pavucontrol pulseaudio pulseaudio-alsa sane                  \
    system-config-printer thunderbird thunderbird-i18n-ja ttf-inconsolata    \
    vlc xbindkeys xdg-utils                                                  \
    xf86-video-intel xorg-server xorg-xset xsane xsel xterm xvkbd)
vmware=(fuse2 gksu gtkmm linux-headers  ncurses5-compat-libs libcanberra vagrant)
virtualbox=(virtualbox virtualbox-host-modules-arch vagrant nfs-utils)
kvm=(qemu virt-manager ebtables dnsmasq firewalld docker-machine-driver-kvm2 minikube-bin kubectl-bin)
tex=(texlive-langjapanese texlive-core texlive-latexextra texlive-science texlive-pictures)
steam_nvidia=(steam nvidia lib32-nvidia-libgl nvidia-settings \
    lib32-libxtst lib32-gtk2 lib32-libpulse lib32-gdk-pixbuf2 lib32-libva \
    lib32-libvdpau lib32-openal)
java=(jdk intellij-idea-community-edition)
laptop=(network-manager-applet networkmanager)
paint=(krita xf86-input-wacom)
pip3=(icalendar arrow progressbar2 feedparser neovim virtualenv websocket-client)
npm=(neovim)
gem=(neovim github-pages tmuxinator)

