#!/bin/bash -e

dir=/home/noyuno/cert.recv
mkdir -p $dir
touch $dir/trig

move() {
    if [ -e $1 ]; then
        mv $dir/$1 /etc/letsencrypt/noyuno.space-0001/$1
    fi
}

while inotifywait -e MODIFY -e CREATE $dir/finish ; do
    move fullchain.pem
    move privkey.pem
done

